name: qi_project_schedule
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
